### **Downloading audio files**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install youtube_dl

     |████████████████████████████████| 1.9MB 6.7MB/s 


In [2]:
temp_str = []
with open('/content/drive/MyDrive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/data-files/csv_files/unbalanced_train_segments.csv', 'r') as f:
    temp_str = f.readlines()

In [4]:
print('Total audio clips :')
print(len(temp_str))

Total audio clips :
2041792


In [ ]:
!python /content/drive/MyDrive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/audio_retrieval.py

Streaming output truncated to the last 5000 lines.
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2016-05-02T09:16:57.000000Z
  Duration: 00:05:03.09, start: 0.000000, bitrate: 127 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 4 kb/s (default)
    Metadata:
      creation_time   : 2016-05-02T09:16:57.000000Z
      handler_name    : SoundHandler
Output #0, mp4, to '1781_Pop_music.mp4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    encoder         : Lavf57.83.100
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 4 kb/s (default)
    Metadata:
      creation_time   : 2016-05-02T09:16:57.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
size=     156kB time=00:00:09.98 bitrate= 128.2kbits/s speed=92.2x    
video:0kB audio:154kB subtitle

In [5]:
import pandas as pd
music_list=pd.read_csv('/content/drive/MyDrive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/music_list.csv')

In [6]:
music_list.head()

url  start_time  end_time    class_label
0  --1rvyPa8UM        40.0      50.0  Hip_hop_music
1  --4kp9W7cNY       160.0     170.0         Reggae
2  --6HJzEIsFs        30.0      40.0   Rhythm_blues
3  --AQ3p3ymeE        70.0      80.0     Rock_music
4  --BMVWju1-w        30.0      40.0   Rhythm_blues

In [7]:
print('Number of rows in music list:')
int(music_list.size/4)

Number of rows in music list:


9080

In [8]:
music_list['class_label'].value_counts()

Techno           2892
Pop_music        2002
Rhythm_blues     1604
Rock_music        949
Hip_hop_music     884
Vocal             441
Reggae            308
Name: class_label, dtype: int64

### **Generating spectrograms**

In [ ]:
!python /content/drive/MyDrive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/generate_spectrograms.py

100% 1533/1533 [23:42<00:00,  1.08it/s]


In [9]:
import os
WAV_DIR = '/content/drive/MyDrive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/wav_files/'
IMG_DIR = '/content/drive/MyDrive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/spectrogram_images/'
wav_files = os.listdir(WAV_DIR)
print('Total number of .wav files downloaded:')
len(wav_files)

Total number of .wav files downloaded:


1533

In [10]:
count=[]
for st in wav_files:
  count.append(st.split('_')[1])

In [11]:
import numpy as np
count = np.array(count)
np.unique(count,return_counts=True)

(array(['Hip', 'Pop', 'Reggae.wav', 'Rhythm', 'Rock', 'Techno.wav',
        'Vocal.wav'], dtype='<U10'),
 array([112, 392,  29, 348, 161, 402,  89]))

In [ ]:
import librosa
wav_files = os.listdir(WAV_DIR)
lengths=[]
for f in tqdm(wav_files):
  y, sr = librosa.load(WAV_DIR+f, sr = 22050)
  lengths.append(y.shape[0])

In [ ]:
import numpy as np

lengths=np.array(lengths)
np.unique(lengths,return_counts=True)

(array([ 19968,  91648, 114176, 146944, 151552, 155136, 197632, 198656,
        198660, 199168, 199680, 199686, 200192, 200704, 200708, 201216,
        201728, 202752, 203264, 203776, 204288, 204800, 205312, 206848,
        208896, 209408, 209920, 210432, 211456, 211968, 212480, 212992,
        215040, 215552, 216064, 216576, 217088, 218624, 220672, 221184]),
 array([   1,    1,    1,    1,    1,    1,    1,   18,    1,    1,   11,
           1,    1,   56,    1,    1,    3,    1,    2,    1,    1,    3,
           1,    1,    4,    2,    3,    1,    2,    1,    1,    1,    1,
           1,    1,    3,    1,    1,  186, 1213]))

In [12]:
pwd

'/content'

In [13]:
cd /content/drive/MyDrive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre

/content/drive/MyDrive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre


In [14]:
ls

audio_retrieval.py               Music_classification.ipynb
cnn_mel_spectrogram.ipynb        music_list.csv
data-files/                      pickle_files/
df_features.csv                  pred_probas/
feature_based_classifiers.ipynb  saved_models/
generate_spectrograms.py         spectrogram_images/
make_features.ipynb              wav_files/


In [25]:
cd spetrogram_images/

[Errno 2] No such file or directory: 'spetrogram_images/'
/content/drive/My Drive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/spectrogram_images


In [26]:
pwd

'/content/drive/My Drive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/spectrogram_images'

In [27]:
cd ..

/content/drive/My Drive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre


In [29]:
path = '/content/drive/My Drive/IIT_Guwahati/IITG_DigitalSignalProcessorsLab/Music_classification_by_Genre/spectrogram_images'
len(os.listdir(path))

1533